[package]
name = "surf-middleware-cache"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cacache = { git = "https://github.com/zkat/cacache-rs", branch = "latest" }
surf = "1.0.3"
futures = "0.3.1"
serde_json = "1.0.41"
http = "0.1.19"
async-trait = "0.1.17"

[dev-dependencies]
async-attributes = "1.1.1"
